name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
   
  camera: ^0.11.0+2
  image_picker: ^0.8.5+3 
  path_provider: ^2.0.11 
  google_mlkit_commons: any 
  google_mlkit_face_detection: ^0.10.0 # 얼굴 인식 (최신은 0.11.1인데.. 다운그레이드함)
  http: ^1.2.2
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.1
  uuid: ^4.5.1
  http_parser: ^4.0.1
  google_ml_kit: ^0.17.0
  fl_chart: ^0.69.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  table_calendar: ^3.1.2

flutter:

  uses-material-design: true
  assets:  
    - assets/BBI.png
    - assets/BBIloading.png
    - assets/BBImask.png
    - assets/BBIangry.png
    - assets/BBIhappy.png
    - assets/BBIpimple.png
    - assets/BBIsad.png
    - assets/BBIblush.png
    - assets/BBIcongs.png

    # 이모티콘
    - assets/emoji/apple.png
    - assets/emoji/appleG.png
    - assets/emoji/lotion.png
    - assets/emoji/soap.png
    - assets/emoji/heart.png
    - assets/emoji/icc.png
    - assets/emoji/paint.png

    # 기본 사진
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/glogo.png
    - assets/images/pizi.jpg

    # 제품 사진
    - assets/product/carrotCarming.png

    # bsti BBI
    - assets/bstiBBI/O--T.png
    - assets/bstiBBI/D-N-.png
    - assets/bstiBBI/D-P-.png
    - assets/bstiBBI/O--W.png
