name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
   
  camera: ^0.11.0+2
  image_picker: ^0.8.5+3 
  path_provider: ^2.0.11 
  google_mlkit_commons: any 
  google_mlkit_face_detection: ^0.10.0 # 얼굴 인식 (최신은 0.11.1인데.. 다운그레이드함)
  http: ^0.13.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:  
    - assets/emoji/face1.png
    - assets/emoji/face2.png
    - assets/emoji/face3.png
    - assets/emoji/face4.png
    - assets/emoji/face5.png
    - assets/emoji/apple.png
    - assets/emoji/appleG.png
    - assets/emoji/clock.png
    - assets/emoji/lotion.png
    - assets/emoji/soap.png


